// Autogenerated from Pigeon (v24.2.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
      }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> PigeonError {
  return PigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

enum DefenderGuardKind: Int {
  case none = 0
  case sensitive = 1
  case otp = 2
}

/// Generated class from Pigeon that represents data sent in messages.
struct NativeRuntimeState {
  var isForeground: Bool? = nil
  var isScreenCaptured: Bool? = nil
  var isEmulator: Bool? = nil
  var supportsOverlayHardening: Bool? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NativeRuntimeState? {
    let isForeground: Bool? = nilOrValue(pigeonVar_list[0])
    let isScreenCaptured: Bool? = nilOrValue(pigeonVar_list[1])
    let isEmulator: Bool? = nilOrValue(pigeonVar_list[2])
    let supportsOverlayHardening: Bool? = nilOrValue(pigeonVar_list[3])

    return NativeRuntimeState(
      isForeground: isForeground,
      isScreenCaptured: isScreenCaptured,
      isEmulator: isEmulator,
      supportsOverlayHardening: supportsOverlayHardening
    )
  }
  func toList() -> [Any?] {
    return [
      isForeground,
      isScreenCaptured,
      isEmulator,
      supportsOverlayHardening,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct LifecycleSnapshot {
  var lastBackgroundedAtMs: Int64? = nil
  var wasAuthenticated: Bool? = nil
  var activeGuardKind: DefenderGuardKind? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> LifecycleSnapshot? {
    let lastBackgroundedAtMs: Int64? = nilOrValue(pigeonVar_list[0])
    let wasAuthenticated: Bool? = nilOrValue(pigeonVar_list[1])
    let activeGuardKind: DefenderGuardKind? = nilOrValue(pigeonVar_list[2])

    return LifecycleSnapshot(
      lastBackgroundedAtMs: lastBackgroundedAtMs,
      wasAuthenticated: wasAuthenticated,
      activeGuardKind: activeGuardKind
    )
  }
  func toList() -> [Any?] {
    return [
      lastBackgroundedAtMs,
      wasAuthenticated,
      activeGuardKind,
    ]
  }
}

private class DefenderMessagesPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return DefenderGuardKind(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      return NativeRuntimeState.fromList(self.readValue() as! [Any?])
    case 131:
      return LifecycleSnapshot.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class DefenderMessagesPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? DefenderGuardKind {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? NativeRuntimeState {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else if let value = value as? LifecycleSnapshot {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class DefenderMessagesPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return DefenderMessagesPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return DefenderMessagesPigeonCodecWriter(data: data)
  }
}

class DefenderMessagesPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = DefenderMessagesPigeonCodec(readerWriter: DefenderMessagesPigeonCodecReaderWriter())
}

/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol DefenderHostApi {
  func setProtectionState(secureActive: Bool, overlayHardeningActive: Bool) throws
  func getRuntimeState() throws -> NativeRuntimeState
  func saveLifecycleSnapshot(snapshot: LifecycleSnapshot) throws
  func loadLifecycleSnapshot() throws -> LifecycleSnapshot
  func clearLifecycleSnapshot() throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class DefenderHostApiSetup {
  static var codec: FlutterStandardMessageCodec { DefenderMessagesPigeonCodec.shared }
  /// Sets up an instance of `DefenderHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: DefenderHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let setProtectionStateChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_defender.DefenderHostApi.setProtectionState\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setProtectionStateChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let secureActiveArg = args[0] as! Bool
        let overlayHardeningActiveArg = args[1] as! Bool
        do {
          try api.setProtectionState(secureActive: secureActiveArg, overlayHardeningActive: overlayHardeningActiveArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setProtectionStateChannel.setMessageHandler(nil)
    }
    let getRuntimeStateChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_defender.DefenderHostApi.getRuntimeState\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getRuntimeStateChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getRuntimeState()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getRuntimeStateChannel.setMessageHandler(nil)
    }
    let saveLifecycleSnapshotChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_defender.DefenderHostApi.saveLifecycleSnapshot\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      saveLifecycleSnapshotChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let snapshotArg = args[0] as! LifecycleSnapshot
        do {
          try api.saveLifecycleSnapshot(snapshot: snapshotArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      saveLifecycleSnapshotChannel.setMessageHandler(nil)
    }
    let loadLifecycleSnapshotChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_defender.DefenderHostApi.loadLifecycleSnapshot\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      loadLifecycleSnapshotChannel.setMessageHandler { _, reply in
        do {
          let result = try api.loadLifecycleSnapshot()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      loadLifecycleSnapshotChannel.setMessageHandler(nil)
    }
    let clearLifecycleSnapshotChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_defender.DefenderHostApi.clearLifecycleSnapshot\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      clearLifecycleSnapshotChannel.setMessageHandler { _, reply in
        do {
          try api.clearLifecycleSnapshot()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      clearLifecycleSnapshotChannel.setMessageHandler(nil)
    }
  }
}
/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol DefenderFlutterApiProtocol {
  func onScreenshotDetected(completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onScreenCaptureChanged(active activeArg: Bool, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onOverlayViolation(completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onForegroundStateChanged(active activeArg: Bool, completion: @escaping (Result<Void, PigeonError>) -> Void)
}
class DefenderFlutterApi: DefenderFlutterApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: DefenderMessagesPigeonCodec {
    return DefenderMessagesPigeonCodec.shared
  }
  func onScreenshotDetected(completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.flutter_defender.DefenderFlutterApi.onScreenshotDetected\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage(nil) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onScreenCaptureChanged(active activeArg: Bool, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.flutter_defender.DefenderFlutterApi.onScreenCaptureChanged\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([activeArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onOverlayViolation(completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.flutter_defender.DefenderFlutterApi.onOverlayViolation\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage(nil) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onForegroundStateChanged(active activeArg: Bool, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.flutter_defender.DefenderFlutterApi.onForegroundStateChanged\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([activeArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
}
