// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> PigeonError {
  return PigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

private func doubleEqualsDefenderMessages(_ lhs: Double, _ rhs: Double) -> Bool {
  return (lhs.isNaN && rhs.isNaN) || lhs == rhs
}

private func doubleHashDefenderMessages(_ value: Double, _ hasher: inout Hasher) {
  if value.isNaN {
    hasher.combine(0x7FF8000000000000)
  } else {
    // Normalize -0.0 to 0.0
    hasher.combine(value == 0 ? 0 : value)
  }
}

func deepEqualsDefenderMessages(_ lhs: Any?, _ rhs: Any?) -> Bool {
  let cleanLhs = nilOrValue(lhs) as Any?
  let cleanRhs = nilOrValue(rhs) as Any?
  switch (cleanLhs, cleanRhs) {
  case (nil, nil):
    return true

  case (nil, _), (_, nil):
    return false

  case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
    return true

  case is (Void, Void):
    return true

  case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
    guard lhsArray.count == rhsArray.count else { return false }
    for (index, element) in lhsArray.enumerated() {
      if !deepEqualsDefenderMessages(element, rhsArray[index]) {
        return false
      }
    }
    return true

  case (let lhsArray, let rhsArray) as ([Double], [Double]):
    guard lhsArray.count == rhsArray.count else { return false }
    for (index, element) in lhsArray.enumerated() {
      if !doubleEqualsDefenderMessages(element, rhsArray[index]) {
        return false
      }
    }
    return true

  case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
    guard lhsDictionary.count == rhsDictionary.count else { return false }
    for (lhsKey, lhsValue) in lhsDictionary {
      var found = false
      for (rhsKey, rhsValue) in rhsDictionary {
        if deepEqualsDefenderMessages(lhsKey, rhsKey) {
          if deepEqualsDefenderMessages(lhsValue, rhsValue) {
            found = true
            break
          } else {
            return false
          }
        }
      }
      if !found { return false }
    }
    return true

  case (let lhs as Double, let rhs as Double):
    return doubleEqualsDefenderMessages(lhs, rhs)

  case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
    return lhsHashable == rhsHashable

  default:
    return false
  }
}

func deepHashDefenderMessages(value: Any?, hasher: inout Hasher) {
  let cleanValue = nilOrValue(value) as Any?
  if let cleanValue = cleanValue {
    if let doubleValue = cleanValue as? Double {
      doubleHashDefenderMessages(doubleValue, &hasher)
    } else if let valueList = cleanValue as? [Any?] {
      for item in valueList {
        deepHashDefenderMessages(value: item, hasher: &hasher)
      }
    } else if let valueList = cleanValue as? [Double] {
      for item in valueList {
        doubleHashDefenderMessages(item, &hasher)
      }
    } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
      var result = 0
      for (key, value) in valueDict {
        var entryKeyHasher = Hasher()
        deepHashDefenderMessages(value: key, hasher: &entryKeyHasher)
        var entryValueHasher = Hasher()
        deepHashDefenderMessages(value: value, hasher: &entryValueHasher)
        result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
      }
      hasher.combine(result)
    } else if let hashableValue = cleanValue as? AnyHashable {
      hasher.combine(hashableValue)
    } else {
      hasher.combine(String(describing: cleanValue))
    }
  } else {
    hasher.combine(0)
  }
}


enum DefenderGuardKind: Int {
  case none = 0
  case sensitive = 1
  case otp = 2
}

/// Generated class from Pigeon that represents data sent in messages.
struct NativeRuntimeState: Hashable {
  var isForeground: Bool? = nil
  var isScreenCaptured: Bool? = nil
  var isEmulator: Bool? = nil
  var supportsOverlayHardening: Bool? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NativeRuntimeState? {
    let isForeground: Bool? = nilOrValue(pigeonVar_list[0])
    let isScreenCaptured: Bool? = nilOrValue(pigeonVar_list[1])
    let isEmulator: Bool? = nilOrValue(pigeonVar_list[2])
    let supportsOverlayHardening: Bool? = nilOrValue(pigeonVar_list[3])

    return NativeRuntimeState(
      isForeground: isForeground,
      isScreenCaptured: isScreenCaptured,
      isEmulator: isEmulator,
      supportsOverlayHardening: supportsOverlayHardening
    )
  }
  func toList() -> [Any?] {
    return [
      isForeground,
      isScreenCaptured,
      isEmulator,
      supportsOverlayHardening,
    ]
  }
  static func == (lhs: NativeRuntimeState, rhs: NativeRuntimeState) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsDefenderMessages(lhs.isForeground, rhs.isForeground) && deepEqualsDefenderMessages(lhs.isScreenCaptured, rhs.isScreenCaptured) && deepEqualsDefenderMessages(lhs.isEmulator, rhs.isEmulator) && deepEqualsDefenderMessages(lhs.supportsOverlayHardening, rhs.supportsOverlayHardening)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("NativeRuntimeState")
    deepHashDefenderMessages(value: isForeground, hasher: &hasher)
    deepHashDefenderMessages(value: isScreenCaptured, hasher: &hasher)
    deepHashDefenderMessages(value: isEmulator, hasher: &hasher)
    deepHashDefenderMessages(value: supportsOverlayHardening, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct LifecycleSnapshot: Hashable {
  var lastBackgroundedAtMs: Int64? = nil
  var wasAuthenticated: Bool? = nil
  var activeGuardKind: DefenderGuardKind? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> LifecycleSnapshot? {
    let lastBackgroundedAtMs: Int64? = nilOrValue(pigeonVar_list[0])
    let wasAuthenticated: Bool? = nilOrValue(pigeonVar_list[1])
    let activeGuardKind: DefenderGuardKind? = nilOrValue(pigeonVar_list[2])

    return LifecycleSnapshot(
      lastBackgroundedAtMs: lastBackgroundedAtMs,
      wasAuthenticated: wasAuthenticated,
      activeGuardKind: activeGuardKind
    )
  }
  func toList() -> [Any?] {
    return [
      lastBackgroundedAtMs,
      wasAuthenticated,
      activeGuardKind,
    ]
  }
  static func == (lhs: LifecycleSnapshot, rhs: LifecycleSnapshot) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsDefenderMessages(lhs.lastBackgroundedAtMs, rhs.lastBackgroundedAtMs) && deepEqualsDefenderMessages(lhs.wasAuthenticated, rhs.wasAuthenticated) && deepEqualsDefenderMessages(lhs.activeGuardKind, rhs.activeGuardKind)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("LifecycleSnapshot")
    deepHashDefenderMessages(value: lastBackgroundedAtMs, hasher: &hasher)
    deepHashDefenderMessages(value: wasAuthenticated, hasher: &hasher)
    deepHashDefenderMessages(value: activeGuardKind, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct AdvancedSecuritySignals: Hashable {
  var rootedOrJailbroken: Bool? = nil
  var proxyEnabled: Bool? = nil
  var vpnEnabled: Bool? = nil
  var debuggerAttached: Bool? = nil
  var tamperingDetected: Bool? = nil
  var tamperingDetails: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> AdvancedSecuritySignals? {
    let rootedOrJailbroken: Bool? = nilOrValue(pigeonVar_list[0])
    let proxyEnabled: Bool? = nilOrValue(pigeonVar_list[1])
    let vpnEnabled: Bool? = nilOrValue(pigeonVar_list[2])
    let debuggerAttached: Bool? = nilOrValue(pigeonVar_list[3])
    let tamperingDetected: Bool? = nilOrValue(pigeonVar_list[4])
    let tamperingDetails: String? = nilOrValue(pigeonVar_list[5])

    return AdvancedSecuritySignals(
      rootedOrJailbroken: rootedOrJailbroken,
      proxyEnabled: proxyEnabled,
      vpnEnabled: vpnEnabled,
      debuggerAttached: debuggerAttached,
      tamperingDetected: tamperingDetected,
      tamperingDetails: tamperingDetails
    )
  }
  func toList() -> [Any?] {
    return [
      rootedOrJailbroken,
      proxyEnabled,
      vpnEnabled,
      debuggerAttached,
      tamperingDetected,
      tamperingDetails,
    ]
  }
  static func == (lhs: AdvancedSecuritySignals, rhs: AdvancedSecuritySignals) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsDefenderMessages(lhs.rootedOrJailbroken, rhs.rootedOrJailbroken) && deepEqualsDefenderMessages(lhs.proxyEnabled, rhs.proxyEnabled) && deepEqualsDefenderMessages(lhs.vpnEnabled, rhs.vpnEnabled) && deepEqualsDefenderMessages(lhs.debuggerAttached, rhs.debuggerAttached) && deepEqualsDefenderMessages(lhs.tamperingDetected, rhs.tamperingDetected) && deepEqualsDefenderMessages(lhs.tamperingDetails, rhs.tamperingDetails)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("AdvancedSecuritySignals")
    deepHashDefenderMessages(value: rootedOrJailbroken, hasher: &hasher)
    deepHashDefenderMessages(value: proxyEnabled, hasher: &hasher)
    deepHashDefenderMessages(value: vpnEnabled, hasher: &hasher)
    deepHashDefenderMessages(value: debuggerAttached, hasher: &hasher)
    deepHashDefenderMessages(value: tamperingDetected, hasher: &hasher)
    deepHashDefenderMessages(value: tamperingDetails, hasher: &hasher)
  }
}

private class DefenderMessagesPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return DefenderGuardKind(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      return NativeRuntimeState.fromList(self.readValue() as! [Any?])
    case 131:
      return LifecycleSnapshot.fromList(self.readValue() as! [Any?])
    case 132:
      return AdvancedSecuritySignals.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class DefenderMessagesPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? DefenderGuardKind {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? NativeRuntimeState {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else if let value = value as? LifecycleSnapshot {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else if let value = value as? AdvancedSecuritySignals {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class DefenderMessagesPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return DefenderMessagesPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return DefenderMessagesPigeonCodecWriter(data: data)
  }
}

class DefenderMessagesPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = DefenderMessagesPigeonCodec(readerWriter: DefenderMessagesPigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol DefenderHostApi {
  func setProtectionState(secureActive: Bool, overlayHardeningActive: Bool) throws
  func getRuntimeState() throws -> NativeRuntimeState
  func getAdvancedSecuritySignals(completion: @escaping (Result<AdvancedSecuritySignals, Error>) -> Void)
  func secureWrite(key: String, value: String, completion: @escaping (Result<Void, Error>) -> Void)
  func secureRead(key: String, completion: @escaping (Result<String?, Error>) -> Void)
  func secureDelete(key: String, completion: @escaping (Result<Void, Error>) -> Void)
  func secureClearAll(completion: @escaping (Result<Void, Error>) -> Void)
  func saveLifecycleSnapshot(snapshot: LifecycleSnapshot) throws
  func loadLifecycleSnapshot() throws -> LifecycleSnapshot
  func clearLifecycleSnapshot() throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class DefenderHostApiSetup {
  static var codec: FlutterStandardMessageCodec { DefenderMessagesPigeonCodec.shared }
  /// Sets up an instance of `DefenderHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: DefenderHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let setProtectionStateChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_defender.DefenderHostApi.setProtectionState\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setProtectionStateChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let secureActiveArg = args[0] as! Bool
        let overlayHardeningActiveArg = args[1] as! Bool
        do {
          try api.setProtectionState(secureActive: secureActiveArg, overlayHardeningActive: overlayHardeningActiveArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setProtectionStateChannel.setMessageHandler(nil)
    }
    let getRuntimeStateChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_defender.DefenderHostApi.getRuntimeState\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getRuntimeStateChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getRuntimeState()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getRuntimeStateChannel.setMessageHandler(nil)
    }
    let getAdvancedSecuritySignalsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_defender.DefenderHostApi.getAdvancedSecuritySignals\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getAdvancedSecuritySignalsChannel.setMessageHandler { _, reply in
        api.getAdvancedSecuritySignals { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getAdvancedSecuritySignalsChannel.setMessageHandler(nil)
    }
    let secureWriteChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_defender.DefenderHostApi.secureWrite\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      secureWriteChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let keyArg = args[0] as! String
        let valueArg = args[1] as! String
        api.secureWrite(key: keyArg, value: valueArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      secureWriteChannel.setMessageHandler(nil)
    }
    let secureReadChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_defender.DefenderHostApi.secureRead\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      secureReadChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let keyArg = args[0] as! String
        api.secureRead(key: keyArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      secureReadChannel.setMessageHandler(nil)
    }
    let secureDeleteChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_defender.DefenderHostApi.secureDelete\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      secureDeleteChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let keyArg = args[0] as! String
        api.secureDelete(key: keyArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      secureDeleteChannel.setMessageHandler(nil)
    }
    let secureClearAllChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_defender.DefenderHostApi.secureClearAll\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      secureClearAllChannel.setMessageHandler { _, reply in
        api.secureClearAll { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      secureClearAllChannel.setMessageHandler(nil)
    }
    let saveLifecycleSnapshotChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_defender.DefenderHostApi.saveLifecycleSnapshot\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      saveLifecycleSnapshotChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let snapshotArg = args[0] as! LifecycleSnapshot
        do {
          try api.saveLifecycleSnapshot(snapshot: snapshotArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      saveLifecycleSnapshotChannel.setMessageHandler(nil)
    }
    let loadLifecycleSnapshotChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_defender.DefenderHostApi.loadLifecycleSnapshot\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      loadLifecycleSnapshotChannel.setMessageHandler { _, reply in
        do {
          let result = try api.loadLifecycleSnapshot()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      loadLifecycleSnapshotChannel.setMessageHandler(nil)
    }
    let clearLifecycleSnapshotChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_defender.DefenderHostApi.clearLifecycleSnapshot\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      clearLifecycleSnapshotChannel.setMessageHandler { _, reply in
        do {
          try api.clearLifecycleSnapshot()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      clearLifecycleSnapshotChannel.setMessageHandler(nil)
    }
  }
}
/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol DefenderFlutterApiProtocol {
  func onScreenshotDetected(completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onScreenCaptureChanged(active activeArg: Bool, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onOverlayViolation(completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onOverlayCleared(completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onForegroundStateChanged(active activeArg: Bool, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onWindowFocusChanged(hasFocus hasFocusArg: Bool, completion: @escaping (Result<Void, PigeonError>) -> Void)
}
class DefenderFlutterApi: DefenderFlutterApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: DefenderMessagesPigeonCodec {
    return DefenderMessagesPigeonCodec.shared
  }
  func onScreenshotDetected(completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.flutter_defender.DefenderFlutterApi.onScreenshotDetected\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage(nil) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onScreenCaptureChanged(active activeArg: Bool, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.flutter_defender.DefenderFlutterApi.onScreenCaptureChanged\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([activeArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onOverlayViolation(completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.flutter_defender.DefenderFlutterApi.onOverlayViolation\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage(nil) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onOverlayCleared(completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.flutter_defender.DefenderFlutterApi.onOverlayCleared\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage(nil) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onForegroundStateChanged(active activeArg: Bool, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.flutter_defender.DefenderFlutterApi.onForegroundStateChanged\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([activeArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onWindowFocusChanged(hasFocus hasFocusArg: Bool, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.flutter_defender.DefenderFlutterApi.onWindowFocusChanged\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([hasFocusArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
}
