// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package aleem.flutter.defender

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object DefenderMessagesPigeonUtils {

  fun createConnectionError(channelName: String): FlutterError {
    return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")  }

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

enum class DefenderGuardKind(val raw: Int) {
  NONE(0),
  SENSITIVE(1),
  OTP(2);

  companion object {
    fun ofRaw(raw: Int): DefenderGuardKind? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class NativeRuntimeState (
  val isForeground: Boolean? = null,
  val isScreenCaptured: Boolean? = null,
  val isEmulator: Boolean? = null,
  val supportsOverlayHardening: Boolean? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NativeRuntimeState {
      val isForeground = pigeonVar_list[0] as Boolean?
      val isScreenCaptured = pigeonVar_list[1] as Boolean?
      val isEmulator = pigeonVar_list[2] as Boolean?
      val supportsOverlayHardening = pigeonVar_list[3] as Boolean?
      return NativeRuntimeState(isForeground, isScreenCaptured, isEmulator, supportsOverlayHardening)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      isForeground,
      isScreenCaptured,
      isEmulator,
      supportsOverlayHardening,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as NativeRuntimeState
    return DefenderMessagesPigeonUtils.deepEquals(this.isForeground, other.isForeground) && DefenderMessagesPigeonUtils.deepEquals(this.isScreenCaptured, other.isScreenCaptured) && DefenderMessagesPigeonUtils.deepEquals(this.isEmulator, other.isEmulator) && DefenderMessagesPigeonUtils.deepEquals(this.supportsOverlayHardening, other.supportsOverlayHardening)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + DefenderMessagesPigeonUtils.deepHash(this.isForeground)
    result = 31 * result + DefenderMessagesPigeonUtils.deepHash(this.isScreenCaptured)
    result = 31 * result + DefenderMessagesPigeonUtils.deepHash(this.isEmulator)
    result = 31 * result + DefenderMessagesPigeonUtils.deepHash(this.supportsOverlayHardening)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class LifecycleSnapshot (
  val lastBackgroundedAtMs: Long? = null,
  val wasAuthenticated: Boolean? = null,
  val activeGuardKind: DefenderGuardKind? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): LifecycleSnapshot {
      val lastBackgroundedAtMs = pigeonVar_list[0] as Long?
      val wasAuthenticated = pigeonVar_list[1] as Boolean?
      val activeGuardKind = pigeonVar_list[2] as DefenderGuardKind?
      return LifecycleSnapshot(lastBackgroundedAtMs, wasAuthenticated, activeGuardKind)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      lastBackgroundedAtMs,
      wasAuthenticated,
      activeGuardKind,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as LifecycleSnapshot
    return DefenderMessagesPigeonUtils.deepEquals(this.lastBackgroundedAtMs, other.lastBackgroundedAtMs) && DefenderMessagesPigeonUtils.deepEquals(this.wasAuthenticated, other.wasAuthenticated) && DefenderMessagesPigeonUtils.deepEquals(this.activeGuardKind, other.activeGuardKind)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + DefenderMessagesPigeonUtils.deepHash(this.lastBackgroundedAtMs)
    result = 31 * result + DefenderMessagesPigeonUtils.deepHash(this.wasAuthenticated)
    result = 31 * result + DefenderMessagesPigeonUtils.deepHash(this.activeGuardKind)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class AdvancedSecuritySignals (
  val rootedOrJailbroken: Boolean? = null,
  val proxyEnabled: Boolean? = null,
  val vpnEnabled: Boolean? = null,
  val debuggerAttached: Boolean? = null,
  val tamperingDetected: Boolean? = null,
  val tamperingDetails: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): AdvancedSecuritySignals {
      val rootedOrJailbroken = pigeonVar_list[0] as Boolean?
      val proxyEnabled = pigeonVar_list[1] as Boolean?
      val vpnEnabled = pigeonVar_list[2] as Boolean?
      val debuggerAttached = pigeonVar_list[3] as Boolean?
      val tamperingDetected = pigeonVar_list[4] as Boolean?
      val tamperingDetails = pigeonVar_list[5] as String?
      return AdvancedSecuritySignals(rootedOrJailbroken, proxyEnabled, vpnEnabled, debuggerAttached, tamperingDetected, tamperingDetails)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      rootedOrJailbroken,
      proxyEnabled,
      vpnEnabled,
      debuggerAttached,
      tamperingDetected,
      tamperingDetails,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as AdvancedSecuritySignals
    return DefenderMessagesPigeonUtils.deepEquals(this.rootedOrJailbroken, other.rootedOrJailbroken) && DefenderMessagesPigeonUtils.deepEquals(this.proxyEnabled, other.proxyEnabled) && DefenderMessagesPigeonUtils.deepEquals(this.vpnEnabled, other.vpnEnabled) && DefenderMessagesPigeonUtils.deepEquals(this.debuggerAttached, other.debuggerAttached) && DefenderMessagesPigeonUtils.deepEquals(this.tamperingDetected, other.tamperingDetected) && DefenderMessagesPigeonUtils.deepEquals(this.tamperingDetails, other.tamperingDetails)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + DefenderMessagesPigeonUtils.deepHash(this.rootedOrJailbroken)
    result = 31 * result + DefenderMessagesPigeonUtils.deepHash(this.proxyEnabled)
    result = 31 * result + DefenderMessagesPigeonUtils.deepHash(this.vpnEnabled)
    result = 31 * result + DefenderMessagesPigeonUtils.deepHash(this.debuggerAttached)
    result = 31 * result + DefenderMessagesPigeonUtils.deepHash(this.tamperingDetected)
    result = 31 * result + DefenderMessagesPigeonUtils.deepHash(this.tamperingDetails)
    return result
  }
}
private open class DefenderMessagesPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          DefenderGuardKind.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NativeRuntimeState.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          LifecycleSnapshot.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          AdvancedSecuritySignals.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is DefenderGuardKind -> {
        stream.write(129)
        writeValue(stream, value.raw.toLong())
      }
      is NativeRuntimeState -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is LifecycleSnapshot -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is AdvancedSecuritySignals -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface DefenderHostApi {
  fun setProtectionState(secureActive: Boolean, overlayHardeningActive: Boolean)
  fun getRuntimeState(): NativeRuntimeState
  fun getAdvancedSecuritySignals(callback: (Result<AdvancedSecuritySignals>) -> Unit)
  fun secureWrite(key: String, value: String, callback: (Result<Unit>) -> Unit)
  fun secureRead(key: String, callback: (Result<String?>) -> Unit)
  fun secureDelete(key: String, callback: (Result<Unit>) -> Unit)
  fun secureClearAll(callback: (Result<Unit>) -> Unit)
  fun saveLifecycleSnapshot(snapshot: LifecycleSnapshot)
  fun loadLifecycleSnapshot(): LifecycleSnapshot
  fun clearLifecycleSnapshot()

  companion object {
    /** The codec used by DefenderHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      DefenderMessagesPigeonCodec()
    }
    /** Sets up an instance of `DefenderHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: DefenderHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_defender.DefenderHostApi.setProtectionState$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val secureActiveArg = args[0] as Boolean
            val overlayHardeningActiveArg = args[1] as Boolean
            val wrapped: List<Any?> = try {
              api.setProtectionState(secureActiveArg, overlayHardeningActiveArg)
              listOf(null)
            } catch (exception: Throwable) {
              DefenderMessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_defender.DefenderHostApi.getRuntimeState$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getRuntimeState())
            } catch (exception: Throwable) {
              DefenderMessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_defender.DefenderHostApi.getAdvancedSecuritySignals$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.getAdvancedSecuritySignals{ result: Result<AdvancedSecuritySignals> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(DefenderMessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(DefenderMessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_defender.DefenderHostApi.secureWrite$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val keyArg = args[0] as String
            val valueArg = args[1] as String
            api.secureWrite(keyArg, valueArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(DefenderMessagesPigeonUtils.wrapError(error))
              } else {
                reply.reply(DefenderMessagesPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_defender.DefenderHostApi.secureRead$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val keyArg = args[0] as String
            api.secureRead(keyArg) { result: Result<String?> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(DefenderMessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(DefenderMessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_defender.DefenderHostApi.secureDelete$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val keyArg = args[0] as String
            api.secureDelete(keyArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(DefenderMessagesPigeonUtils.wrapError(error))
              } else {
                reply.reply(DefenderMessagesPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_defender.DefenderHostApi.secureClearAll$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.secureClearAll{ result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(DefenderMessagesPigeonUtils.wrapError(error))
              } else {
                reply.reply(DefenderMessagesPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_defender.DefenderHostApi.saveLifecycleSnapshot$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val snapshotArg = args[0] as LifecycleSnapshot
            val wrapped: List<Any?> = try {
              api.saveLifecycleSnapshot(snapshotArg)
              listOf(null)
            } catch (exception: Throwable) {
              DefenderMessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_defender.DefenderHostApi.loadLifecycleSnapshot$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.loadLifecycleSnapshot())
            } catch (exception: Throwable) {
              DefenderMessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_defender.DefenderHostApi.clearLifecycleSnapshot$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.clearLifecycleSnapshot()
              listOf(null)
            } catch (exception: Throwable) {
              DefenderMessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated class from Pigeon that represents Flutter messages that can be called from Kotlin. */
class DefenderFlutterApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by DefenderFlutterApi. */
    val codec: MessageCodec<Any?> by lazy {
      DefenderMessagesPigeonCodec()
    }
  }
  fun onScreenshotDetected(callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.flutter_defender.DefenderFlutterApi.onScreenshotDetected$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(null) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(DefenderMessagesPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  fun onScreenCaptureChanged(activeArg: Boolean, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.flutter_defender.DefenderFlutterApi.onScreenCaptureChanged$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(activeArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(DefenderMessagesPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  fun onOverlayViolation(callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.flutter_defender.DefenderFlutterApi.onOverlayViolation$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(null) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(DefenderMessagesPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  fun onOverlayCleared(callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.flutter_defender.DefenderFlutterApi.onOverlayCleared$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(null) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(DefenderMessagesPigeonUtils.createConnectionError(channelName)))
      }
    }
  }
  fun onForegroundStateChanged(activeArg: Boolean, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.flutter_defender.DefenderFlutterApi.onForegroundStateChanged$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(activeArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(DefenderMessagesPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  fun onWindowFocusChanged(hasFocusArg: Boolean, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.flutter_defender.DefenderFlutterApi.onWindowFocusChanged$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(hasFocusArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(DefenderMessagesPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
}
