// Autogenerated from Pigeon (v24.2.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package aleem.flutter.defender

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer

private fun wrapResult(result: Any?): List<Any?> {
  return listOf(result)
}

private fun wrapError(exception: Throwable): List<Any?> {
  return if (exception is FlutterError) {
    listOf(
      exception.code,
      exception.message,
      exception.details
    )
  } else {
    listOf(
      exception.javaClass.simpleName,
      exception.toString(),
      "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
    )
  }
}

private fun createConnectionError(channelName: String): FlutterError {
  return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

enum class DefenderGuardKind(val raw: Int) {
  NONE(0),
  SENSITIVE(1),
  OTP(2);

  companion object {
    fun ofRaw(raw: Int): DefenderGuardKind? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class NativeRuntimeState (
  val isForeground: Boolean? = null,
  val isScreenCaptured: Boolean? = null,
  val isEmulator: Boolean? = null,
  val supportsOverlayHardening: Boolean? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NativeRuntimeState {
      val isForeground = pigeonVar_list[0] as Boolean?
      val isScreenCaptured = pigeonVar_list[1] as Boolean?
      val isEmulator = pigeonVar_list[2] as Boolean?
      val supportsOverlayHardening = pigeonVar_list[3] as Boolean?
      return NativeRuntimeState(isForeground, isScreenCaptured, isEmulator, supportsOverlayHardening)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      isForeground,
      isScreenCaptured,
      isEmulator,
      supportsOverlayHardening,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class LifecycleSnapshot (
  val lastBackgroundedAtMs: Long? = null,
  val wasAuthenticated: Boolean? = null,
  val activeGuardKind: DefenderGuardKind? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): LifecycleSnapshot {
      val lastBackgroundedAtMs = pigeonVar_list[0] as Long?
      val wasAuthenticated = pigeonVar_list[1] as Boolean?
      val activeGuardKind = pigeonVar_list[2] as DefenderGuardKind?
      return LifecycleSnapshot(lastBackgroundedAtMs, wasAuthenticated, activeGuardKind)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      lastBackgroundedAtMs,
      wasAuthenticated,
      activeGuardKind,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class AdvancedSecuritySignals (
  val rootedOrJailbroken: Boolean? = null,
  val proxyEnabled: Boolean? = null,
  val vpnEnabled: Boolean? = null,
  val debuggerAttached: Boolean? = null,
  val tamperingDetected: Boolean? = null,
  val tamperingDetails: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): AdvancedSecuritySignals {
      val rootedOrJailbroken = pigeonVar_list[0] as Boolean?
      val proxyEnabled = pigeonVar_list[1] as Boolean?
      val vpnEnabled = pigeonVar_list[2] as Boolean?
      val debuggerAttached = pigeonVar_list[3] as Boolean?
      val tamperingDetected = pigeonVar_list[4] as Boolean?
      val tamperingDetails = pigeonVar_list[5] as String?
      return AdvancedSecuritySignals(rootedOrJailbroken, proxyEnabled, vpnEnabled, debuggerAttached, tamperingDetected, tamperingDetails)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      rootedOrJailbroken,
      proxyEnabled,
      vpnEnabled,
      debuggerAttached,
      tamperingDetected,
      tamperingDetails,
    )
  }
}
private open class DefenderMessagesPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          DefenderGuardKind.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NativeRuntimeState.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          LifecycleSnapshot.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          AdvancedSecuritySignals.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is DefenderGuardKind -> {
        stream.write(129)
        writeValue(stream, value.raw)
      }
      is NativeRuntimeState -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is LifecycleSnapshot -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is AdvancedSecuritySignals -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface DefenderHostApi {
  fun setProtectionState(secureActive: Boolean, overlayHardeningActive: Boolean)
  fun getRuntimeState(): NativeRuntimeState
  fun getAdvancedSecuritySignals(): AdvancedSecuritySignals
  fun secureWrite(key: String, value: String)
  fun secureRead(key: String): String?
  fun secureDelete(key: String)
  fun secureClearAll()
  fun saveLifecycleSnapshot(snapshot: LifecycleSnapshot)
  fun loadLifecycleSnapshot(): LifecycleSnapshot
  fun clearLifecycleSnapshot()

  companion object {
    /** The codec used by DefenderHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      DefenderMessagesPigeonCodec()
    }
    /** Sets up an instance of `DefenderHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: DefenderHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_defender.DefenderHostApi.setProtectionState$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val secureActiveArg = args[0] as Boolean
            val overlayHardeningActiveArg = args[1] as Boolean
            val wrapped: List<Any?> = try {
              api.setProtectionState(secureActiveArg, overlayHardeningActiveArg)
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_defender.DefenderHostApi.getRuntimeState$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getRuntimeState())
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_defender.DefenderHostApi.getAdvancedSecuritySignals$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getAdvancedSecuritySignals())
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_defender.DefenderHostApi.secureWrite$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val keyArg = args[0] as String
            val valueArg = args[1] as String
            val wrapped: List<Any?> = try {
              api.secureWrite(keyArg, valueArg)
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_defender.DefenderHostApi.secureRead$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val keyArg = args[0] as String
            val wrapped: List<Any?> = try {
              listOf(api.secureRead(keyArg))
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_defender.DefenderHostApi.secureDelete$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val keyArg = args[0] as String
            val wrapped: List<Any?> = try {
              api.secureDelete(keyArg)
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_defender.DefenderHostApi.secureClearAll$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.secureClearAll()
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_defender.DefenderHostApi.saveLifecycleSnapshot$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val snapshotArg = args[0] as LifecycleSnapshot
            val wrapped: List<Any?> = try {
              api.saveLifecycleSnapshot(snapshotArg)
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_defender.DefenderHostApi.loadLifecycleSnapshot$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.loadLifecycleSnapshot())
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_defender.DefenderHostApi.clearLifecycleSnapshot$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.clearLifecycleSnapshot()
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated class from Pigeon that represents Flutter messages that can be called from Kotlin. */
class DefenderFlutterApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by DefenderFlutterApi. */
    val codec: MessageCodec<Any?> by lazy {
      DefenderMessagesPigeonCodec()
    }
  }
  fun onScreenshotDetected(callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.flutter_defender.DefenderFlutterApi.onScreenshotDetected$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(null) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
  fun onScreenCaptureChanged(activeArg: Boolean, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.flutter_defender.DefenderFlutterApi.onScreenCaptureChanged$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(activeArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
  fun onOverlayViolation(callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.flutter_defender.DefenderFlutterApi.onOverlayViolation$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(null) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
  fun onForegroundStateChanged(activeArg: Boolean, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.flutter_defender.DefenderFlutterApi.onForegroundStateChanged$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(activeArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
}
