// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
  List<Object?>? replyList,
  String channelName, {
  required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}

List<Object?> wrapResponse({
  Object? result,
  PlatformException? error,
  bool empty = false,
}) {
  if (empty) {
    return <Object?>[];
  }
  if (error == null) {
    return <Object?>[result];
  }
  return <Object?>[error.code, error.message, error.details];
}

bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed.every(
          ((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]),
        );
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}

enum DefenderGuardKind { none, sensitive, otp }

class NativeRuntimeState {
  NativeRuntimeState({
    this.isForeground,
    this.isScreenCaptured,
    this.isEmulator,
    this.supportsOverlayHardening,
  });

  bool? isForeground;

  bool? isScreenCaptured;

  bool? isEmulator;

  bool? supportsOverlayHardening;

  List<Object?> _toList() {
    return <Object?>[
      isForeground,
      isScreenCaptured,
      isEmulator,
      supportsOverlayHardening,
    ];
  }

  Object encode() {
    return _toList();
  }

  static NativeRuntimeState decode(Object result) {
    result as List<Object?>;
    return NativeRuntimeState(
      isForeground: result[0] as bool?,
      isScreenCaptured: result[1] as bool?,
      isEmulator: result[2] as bool?,
      supportsOverlayHardening: result[3] as bool?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! NativeRuntimeState || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(isForeground, other.isForeground) &&
        _deepEquals(isScreenCaptured, other.isScreenCaptured) &&
        _deepEquals(isEmulator, other.isEmulator) &&
        _deepEquals(supportsOverlayHardening, other.supportsOverlayHardening);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class LifecycleSnapshot {
  LifecycleSnapshot({
    this.lastBackgroundedAtMs,
    this.wasAuthenticated,
    this.activeGuardKind,
  });

  int? lastBackgroundedAtMs;

  bool? wasAuthenticated;

  DefenderGuardKind? activeGuardKind;

  List<Object?> _toList() {
    return <Object?>[lastBackgroundedAtMs, wasAuthenticated, activeGuardKind];
  }

  Object encode() {
    return _toList();
  }

  static LifecycleSnapshot decode(Object result) {
    result as List<Object?>;
    return LifecycleSnapshot(
      lastBackgroundedAtMs: result[0] as int?,
      wasAuthenticated: result[1] as bool?,
      activeGuardKind: result[2] as DefenderGuardKind?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! LifecycleSnapshot || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(lastBackgroundedAtMs, other.lastBackgroundedAtMs) &&
        _deepEquals(wasAuthenticated, other.wasAuthenticated) &&
        _deepEquals(activeGuardKind, other.activeGuardKind);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class AdvancedSecuritySignals {
  AdvancedSecuritySignals({
    this.rootedOrJailbroken,
    this.proxyEnabled,
    this.vpnEnabled,
    this.debuggerAttached,
    this.tamperingDetected,
    this.tamperingDetails,
  });

  bool? rootedOrJailbroken;

  bool? proxyEnabled;

  bool? vpnEnabled;

  bool? debuggerAttached;

  bool? tamperingDetected;

  String? tamperingDetails;

  List<Object?> _toList() {
    return <Object?>[
      rootedOrJailbroken,
      proxyEnabled,
      vpnEnabled,
      debuggerAttached,
      tamperingDetected,
      tamperingDetails,
    ];
  }

  Object encode() {
    return _toList();
  }

  static AdvancedSecuritySignals decode(Object result) {
    result as List<Object?>;
    return AdvancedSecuritySignals(
      rootedOrJailbroken: result[0] as bool?,
      proxyEnabled: result[1] as bool?,
      vpnEnabled: result[2] as bool?,
      debuggerAttached: result[3] as bool?,
      tamperingDetected: result[4] as bool?,
      tamperingDetails: result[5] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! AdvancedSecuritySignals || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(rootedOrJailbroken, other.rootedOrJailbroken) &&
        _deepEquals(proxyEnabled, other.proxyEnabled) &&
        _deepEquals(vpnEnabled, other.vpnEnabled) &&
        _deepEquals(debuggerAttached, other.debuggerAttached) &&
        _deepEquals(tamperingDetected, other.tamperingDetected) &&
        _deepEquals(tamperingDetails, other.tamperingDetails);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    } else if (value is DefenderGuardKind) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    } else if (value is NativeRuntimeState) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    } else if (value is LifecycleSnapshot) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    } else if (value is AdvancedSecuritySignals) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        final value = readValue(buffer) as int?;
        return value == null ? null : DefenderGuardKind.values[value];
      case 130:
        return NativeRuntimeState.decode(readValue(buffer)!);
      case 131:
        return LifecycleSnapshot.decode(readValue(buffer)!);
      case 132:
        return AdvancedSecuritySignals.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class DefenderHostApi {
  /// Constructor for [DefenderHostApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  DefenderHostApi({
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) : pigeonVar_binaryMessenger = binaryMessenger,
       pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty
           ? '.$messageChannelSuffix'
           : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<void> setProtectionState(
    bool secureActive,
    bool overlayHardeningActive,
  ) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.flutter_defender.DefenderHostApi.setProtectionState$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[secureActive, overlayHardeningActive],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<NativeRuntimeState> getRuntimeState() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.flutter_defender.DefenderHostApi.getRuntimeState$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as NativeRuntimeState;
  }

  Future<AdvancedSecuritySignals> getAdvancedSecuritySignals() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.flutter_defender.DefenderHostApi.getAdvancedSecuritySignals$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as AdvancedSecuritySignals;
  }

  Future<void> secureWrite(String key, String value) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.flutter_defender.DefenderHostApi.secureWrite$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[key, value],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<String?> secureRead(String key) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.flutter_defender.DefenderHostApi.secureRead$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[key],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
    return pigeonVar_replyValue as String?;
  }

  Future<void> secureDelete(String key) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.flutter_defender.DefenderHostApi.secureDelete$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[key],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> secureClearAll() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.flutter_defender.DefenderHostApi.secureClearAll$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<void> saveLifecycleSnapshot(LifecycleSnapshot snapshot) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.flutter_defender.DefenderHostApi.saveLifecycleSnapshot$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[snapshot],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  Future<LifecycleSnapshot> loadLifecycleSnapshot() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.flutter_defender.DefenderHostApi.loadLifecycleSnapshot$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as LifecycleSnapshot;
  }

  Future<void> clearLifecycleSnapshot() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.flutter_defender.DefenderHostApi.clearLifecycleSnapshot$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }
}

abstract class DefenderFlutterApi {
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  void onScreenshotDetected();

  void onScreenCaptureChanged(bool active);

  void onOverlayViolation();

  void onForegroundStateChanged(bool active);

  void onWindowFocusChanged(bool hasFocus);

  static void setUp(
    DefenderFlutterApi? api, {
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) {
    messageChannelSuffix = messageChannelSuffix.isNotEmpty
        ? '.$messageChannelSuffix'
        : '';
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.flutter_defender.DefenderFlutterApi.onScreenshotDetected$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          try {
            api.onScreenshotDetected();
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.flutter_defender.DefenderFlutterApi.onScreenCaptureChanged$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final bool arg_active = args[0]! as bool;
          try {
            api.onScreenCaptureChanged(arg_active);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.flutter_defender.DefenderFlutterApi.onOverlayViolation$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          try {
            api.onOverlayViolation();
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.flutter_defender.DefenderFlutterApi.onForegroundStateChanged$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final bool arg_active = args[0]! as bool;
          try {
            api.onForegroundStateChanged(arg_active);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.flutter_defender.DefenderFlutterApi.onWindowFocusChanged$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final bool arg_hasFocus = args[0]! as bool;
          try {
            api.onWindowFocusChanged(arg_hasFocus);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
  }
}
